version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - ./:/var/www
      - ./:/var/www/html:cached
      - ./Docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
      - ${WEB_PORT}:80
